-- Création de la table des sorts
CREATE TABLE IF NOT EXISTS spells (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    level INTEGER NOT NULL,
    school TEXT,
    casting_time TEXT,
    range TEXT,
    components TEXT,
    duration TEXT,
    combinable INTEGER DEFAULT 0, -- 1 si combinable, 0 sinon
    description TEXT
);

BEGIN TRANSACTION;

-- NIVEAU 0 (Tours de magie)
INSERT INTO spells (name, level, school, casting_time, range, components, duration, combinable, description) VALUES
('Amis', 0, 'enchantement', '1 action', 'personnelle', 'S, M (une petite quantité de maquillage appliquée sur le visage durant l''incantation)', 'concentration, jusqu''à 1 minute', 0, 'Pour la durée du sort, vous avez un avantage à tous vos jets de Charisme effectués contre une créature de votre choix qui n''a pas une attitude hostile envers vous. Lorsque le sort prend fin, la créature réalise que vous avez utilisé la magie pour l''influencer et devient hostile à votre égard. Une créature plutôt violente risque de vous attaquer. D''autres créatures peuvent vous demander de l''argent ou un service (à la discrétion du MD), cela dépend de la nature de l''échange que vous avez eu avec la créature.'),
('Aspersion d''acide', 0, 'invocation', '1 action', '18 mètres', 'V, S', 'instantanée', 0, 'Vous propulsez une bulle d''acide. Choisissez une ou deux créatures que vous pouvez voir, à 1,50 mètre ou moins l''une de l''autre, dans la portée du sort. La cible doit réussir un jet de sauvegarde de Dextérité ou subir 1d6 dégâts d''acide. Les dégâts de ce sort augmentent de 1d6 lorsque vous atteignez le niveau 5 (2d6), le niveau 11 (3d6) et le niveau 17 (4d6).'),
('Assistance', 0, 'divination', '1 action', 'contact', 'V, S', 'concentration, jusqu''à 1 minute', 1, 'Vous touchez une créature consentante. Une fois avant la fin du sort, la cible peut lancer un d4 et ajouter le résultat du dé à un jet de caractéristique de son choix. Elle peut lancer le dé avant ou après avoir effectué son jet de caractéristique. Le sort prend alors fin.'),
('Bouffée de poison', 0, 'invocation', '1 action', '3 mètres', 'V, S', 'instantanée', 0, 'Vous tendez votre paume vers une créature visible dans la portée du sort et vous projetez une bouffée de gaz nocif de votre main. La créature doit réussir un jet de sauvegarde de Constitution ou subir 1d12 dégâts de poison. Les dégâts de ce sort augmentent de 1d12 lorsque vous atteignez le niveau 5 (2d12), le niveau 11 (3d12) et le niveau 17 (4d12).'),
('Contact glacial', 0, 'nécromancie', '1 action', '36 mètres', 'V, S', '1 round', 0, 'Vous créez une main squelettique fantomatique dans l''espace d''une créature à portée. Faites une attaque à distance avec un sort contre la créature pour l''étreindre d''une froideur sépulcrale. Si le coup touche, la cible subit 1d8 dégâts nécrotiques, et elle ne peut récupérer ses points de vie avant le début de votre prochain tour. Jusque-là, la main fantomatique s''accroche à la cible. Si vous ciblez un mort-vivant, il aura également un désavantage à ses jets d''attaque contre vous jusqu''à la fin de votre prochain tour. Les dégâts de ce sort augmentent de 1d8 lorsque vous atteignez le niveau 5 (2d8), le niveau 11 (3d8) et le niveau 17 (4d8).'),
('Contrôle des flammes', 0, 'transmutation', '1 action', '18 mètres', 'S', 'instantanée ou 1 heure (voir ci-dessous)', 1, 'Vous choisissez un feu non magique visible dans la portée du sort de 1,50 mètre d''arête maximum. Vous pouvez l''affecter de l'une des façons suivantes : Vous pouvez faire grossir instantanément le feu de 1,50 mètre dans une direction... Si vous lancez ce sort plusieurs fois, vous pouvez avoir jusqu''à trois de ses effets non-instantanés actifs à la fois, et vous pouvez en dissiper un en une action.'),
('Coup au but', 0, 'divination', '1 action', '9 mètres', 'S', 'concentration, jusqu''à 1 round', 0, 'Vous tendez votre main et pointez un doigt en direction d''une cible à portée. Votre magie vous aide à trouver une petite faille dans les défenses de votre cible. Lors de votre prochain tour, vous obtenez un avantage pour votre premier jet d''attaque contre la cible, à condition que le sort ne soit pas déjà terminé.'),
('Coup de tonnerre', 0, 'évocation', '1 action', '1,50 mètre', 'S', 'instantanée', 0, 'Vous créez un bruit de tonnerre qui peut être entendu jusqu''à 30 mètres. Hormis vous-même, toute créature à portée doit réussir un jet de sauvegarde de Constitution ou subir 1d6 dégâts de tonnerre. Les dégâts de ce sort augmentent de 1d6 lorsque vous atteignez le niveau 5 (2d6), le niveau 11 (3d6) et le niveau 17 (4d6).'),
('Décharge occulte', 0, 'évocation', '1 action', '36 mètres', 'V, S', 'instantanée', 0, 'Un rayon d''énergie crépitante zigzague jusqu''à une créature à portée. Effectuez une attaque à distance avec un sort contre la cible. En cas de réussite, la cible subit 1d10 dégâts de force. Ce sort crée plus d''un rayon lorsque vous montez en niveau : deux rayons au niveau 5, trois rayons au niveau 11, et quatre rayons au niveau 17.'),
('Druidisme', 0, 'transmutation', '1 action', '9 mètres', 'V, S', 'instantanée', 0, 'En murmurant aux esprits de la nature, vous créez l''un des effets suivants, dans la portée du sort : effet sensoriel météo, floraison immédiate, effet sensoriel minime, ou allumer/éteindre une petite flamme.'),
('Éclat gravitationnel', 0, 'inconnu', '1 action', 'm/t du joueur', 'S', '1t', 0, 'Petite poussée qui fait reculer un ennemi de 1,5 m. Niveau supérieur : +0.5m/lv de joueur.'),
('Embrasement', 0, 'invocation', '1 action', '18 mètres', 'V, S', 'concentration, jusqu''à 1 minute', 0, 'Vous créez un feu de joie sur un sol visible dans la portée du sort. Jusqu''à ce que le sort finisse, le feu de joie magique occupe un cube de 1,50 mètre d''arête. Dégâts : 1d8 feu (JS Dex). Augmente au niv 5, 11, 17.'),
('Éruption de lames', 0, 'invocation', '1 action', 'personnelle (rayon de 1,50 mètre)', 'V', 'instantanée', 0, 'Vous créez temporairement un cercle de lames spectrales autour de vous. Toutes les autres créatures dans un rayon de 1,50 mètre doivent réussir un JS Dextérité ou subir 1d6 dégâts de force (augmente au niv 5, 11, 17).'),
('Façonnage de l''eau', 0, 'transmutation', '1 action', '9 mètres', 'S', 'instantanée ou 1 heure', 1, 'Manipulez un cube d''eau de 1,50 m (déplacer, former, changer couleur/opacité, geler). Deux effets non-instantanés max.'),
('Façonnage de la terre', 0, 'transmutation', '1 action', '9 mètres', 'S', 'instantanée ou 1 heure', 1, 'Manipulez la terre/pierre (creuser/déplacer terre meuble, écrire/dessiner, terrain difficile/normal). Deux effets non-instantanés max.'),
('Ferrage foudroyant', 0, 'évocation', '1 action', 'personnelle (rayon de 4,50 mètres)', 'V', 'instantanée', 0, 'Décharge foudroyante attirant une cible sur 3m. JS Force ou subit 1d8 dégâts de foudre si à 1,50m ou moins.'),
('Flamme sacrée', 0, 'évocation', '1 action', '18 mètres', 'V, S', 'instantanée', 0, 'Un rayonnement descend sur une créature visible. JS Dextérité ou 1d8 dégâts radiants (pas de bénéfice d''abri).'),
('Flammes', 0, 'invocation', '1 action', 'personnelle', 'V, S', '10 minutes', 0, 'Produit une flamme dans la main (lumière 3m). Peut être jetée à 9m pour 1d8 dégâts de feu.'),
('Fouet épineux', 0, 'transmutation', '1 action', '9 mètres', 'V, S, M (la tige d''une plante avec des épines)', 'instantanée', 0, 'Attaque au corps à corps avec un sort. 1d6 dégâts perforants et tire la cible de taille G ou inférieure jusqu''à 3m vers vous.'),
('Gelure', 0, 'évocation', '1 action', '18 mètres', 'V, S', 'instantanée', 0, 'Couche de gel. JS Constitution ou 1d6 dégâts de froid et désavantage au prochain jet d''attaque avant la fin du prochain tour.'),
('Glas', 0, 'nécromancie', '1 action', '18 mètres', 'V, S', 'instantanée', 0, 'Son de cloche painful. JS Sagesse ou 1d8 dégâts nécrotiques (1d12 si la cible n''est pas au max de ses PV).'),
('Gourdin magique', 0, 'transmutation', '1 action bonus', 'contact', 'V, S, M (du gui, une feuille de trèfle et un bâton ou un gourdin)', '1 minute', 1, 'Enchante un bâton/gourdin. Permet d''utiliser la caractéristique d''incantation pour l''attaque et les dégâts (d8). L''arme devient magique.'),
('Illusion mineure', 0, 'illusion', '1 action', '9 mètres', 'S, M (un peu de laine de mouton)', '1 minute', 1, 'Crée un son ou l''image d''un objet (cube de 1,50 m max) à portée.'),
('Infestation', 0, 'invocation', '1 action', '9 mètres', 'V, S, M (une puce vivante)', 'instantanée', 0, 'Nuage de parasites. JS Constitution ou 1d6 dégâts de poison et déplacement aléatoire de 1,50 m (d4).'),
('Lame aux flammes vertes', 0, 'évocation', '1 action', 'personnelle (rayon de 1,50 mètre)', 'S, M (une arme de corps à corps valant au moins 1 pa)', 'instantanée', 0, 'Attaque au corps à corps. En cas de touche, inflige les dégâts normaux et saute sur une 2e cible proche pour des dégâts de feu (modificateur d''incantation).'),
('Lame retentissante', 0, 'évocation', '1 action', 'personnelle (rayon de 1,50 mètre)', 'V, M (une arme de corps à corps valant au moins 1 pa)', '1 round', 0, 'Attaque au corps à corps. Enveloppe la cible d''énergie : si elle se déplace volontairement de 1,50 m+, elle subit 1d8 dégâts de tonnerre.'),
('Lumière', 0, 'évocation', '1 action', 'contact', 'V, M (une luciole ou de la mousse phosphorescente)', '1 heure', 1, 'L''objet touché émet une lumière vive sur 6m et faible sur 6m supplémentaires.'),
('Lumières dansantes', 0, 'évocation', '1 action', '36 mètres', 'V, S, M (phosphore, écorce ou ver luisant)', 'concentration, jusqu''à 1 minute', 1, 'Crée jusqu''à 4 lumières de taille torche ou un humanoïde brillant (lumière faible sur 3m).'),
('Main de mage', 0, 'invocation', '1 action', '9 mètres', 'V, S', '1 minute', 1, 'Invoque une main spectrale capable de manipuler des objets (max 5 kg) jusqu''à 9m.'),
('Manipulation télékinétique', 0, 'inconnu', '1 action', '9m', 'S', '1min', 1, 'Actionner un bouton, ouvrir une porte, ramasser un objet (5Kg et 9m)… comme Main de mage. Niveau supérieur : +2Kg/lv de joueur et +5m/lv de sort.'),
('Message', 0, 'transmutation', '1 action', '36 mètres', 'V, S, M (un petit bout de fil de cuivre)', '1 round', 1, 'Pointe une créature et murmure un message reçu uniquement par elle, qui peut répondre en murmure.'),
('Moquerie cruelle', 0, 'enchantement', '1 action', '18 mètres', 'V', 'instantanée', 0, 'Flot d''insultes. JS Sagesse ou 1d4 dégâts psychiques et désavantage au prochain jet d'attaque.'),
('Mot de radiance', 0, 'évocation', '1 action', '1,50 mètre', 'V, M (un symbole sacré)', 'instantanée', 0, 'Éclat brûlant autour de vous. JS Constitution ou 1d6 dégâts radiants pour les créatures choisies.'),
('Pierre magique', 0, 'transmutation', '1 action bonus', 'contact', 'V, S', '1 minute', 0, 'Enchante jusqu''à 3 cailloux jetables à 18m pour 1d6 + mod. d''incantation dégâts contondants.'),
('Piqûre mentale', 0, 'enchantement', '1 action', '18 mètres', 'V', '1 round', 0, 'JS Intelligence ou 1d6 dégâts psychiques et soustrait 1d4 à sa prochaine sauvegarde.'),
('Poigne électrique', 0, 'évocation', '1 action', 'contact', 'V, S', 'instantanée', 0, 'Attaque au corps à corps avec un sort (avantage si armure métal). 1d8 dégâts de foudre et empêche les réactions.'),
('Poussée mineure', 0, 'inconnu', '1 action', '3m', 'S', '1min', 1, 'Déplace un petit objet de 1 kg dans un rayon de 3 m ou déséquilibre (-2 au prochain jet d’attaque). Niveau supérieur : +1Kg/lv et +3m/lv.'),
('Prestidigitation', 0, 'transmutation', '1 action', '3 mètres', 'V, S', 'jusqu''à 1 heure', 1, 'Tour de magie universel aux multiples effets mineurs (sensory, nettoyer, chauffer/refroidir, babioles...). Max 3 effets actifs.'),
('Protection contre les armes', 0, 'abjuration', '1 action', 'personnelle', 'V, S', '1 round', 0, 'Résistance contre les dégâts contondants, tranchants et perforants infligés par des attaques d''armes jusqu''à la fin du prochain tour.'),
('Rayon de givre', 0, 'évocation', '1 action', '18 mètres', 'V, S', 'instantanée', 0, 'Attaque à distance. 1d8 dégâts de froid et vitesse réduite de 3m.'),
('Réparation', 0, 'transmutation', '1 minute', 'contact', 'V, S, M (deux aimants)', 'instantanée', 1, 'Répare une fissure/déchirure d''au plus 30 cm sur un objet.'),
('Résistance', 0, 'abjuration', '1 action', 'contact', 'V, S, M (une cape miniature)', 'concentration, jusqu''à 1 minute', 0, 'La cible consentante peut ajouter 1d4 à un jet de sauvegarde de son choix.'),
('Saute de vent', 0, 'transmutation', '1 action', '9 mètres', 'V, S', 'instantanée', 1, 'Crée un effet d''air à portée : repousse créature (JS Force, 1,5m), déplace un objet (2,5 kg max de 3m) ou effet sensoriel.'),
('Sauvagerie primitive', 0, 'transmutation', '1 action', 'personnelle', 'S', 'instantanée', 0, 'Aiguise dents/ongles. Attaque au corps à corps pour 1d10 dégâts d''acide.'),
('Saisie rapide', 0, 'inconnu', 'réaction', 'm/t du joueur', 'M, S (a crushed button, a small doll, discarded gum wrapper)', 'instantanée', 1, 'Intercepte ou attire un petit objet vers ta main à 30m/s. Niveau supérieur : +10m/s/lv de joueur.'),
('Stabilisation', 0, 'nécromancie', '1 action', 'contact', 'V, S', 'instantanée', 0, 'Rend stable une créature à 0 point de vie.'),
('Thaumaturgie', 0, 'transmutation', '1 action', '9 mètres', 'V', 'jusqu''à 1 minute', 1, 'Manifestation divinement spectaculaire (voix x3, flammes vacillantes, secousse du sol, son instantané, portes fermées/ouvertes). Max 3 effets.'),
('Trait de feu', 0, 'évocation', '1 action', '36 mètres', 'V, S', 'instantanée', 0, 'Attaque à distance avec un sort. 1d10 dégâts de feu (enflamme objets non portés).'),
('Vibration mentale', 0, 'inconnu', '1 action', '18m', 'S, V', 'instantanée', 1, 'Envoie une onde mentale qui inflige 1d6 dégâts psychiques. Niveau supérieur : +6m/lv de sort.'),

-- NIVEAU 1
('Absorption des éléments', 1, 'abjuration', '1 réaction', 'personnelle', 'S', '1 round', 0, 'Réduit les dégâts élémentaires subis (résistance) et ajoute +1d6 dégâts du même type à la prochaine attaque au corps à corps.'),
('Alarme', 1, 'abjuration (rituel)', '1 minute', '9 mètres', 'V, S, M (clochette et fil d''argent)', '8 heures', 0, 'Alerte (mentale ou audible) si une créature touche ou pénètre la zone désignée (cube de 6m).'),
('Amitié avec les animaux', 1, 'enchantement', '1 action', '9 mètres', 'V, S, M (morceau de nourriture)', '24 heures', 0, 'Charme une bête (Int < 4). JS Sagesse.'),
('Appel de familier', 1, 'invocation (rituel)', '1 heure', '3 mètres', 'V, S, M (charbon, encens, herbes 10 po)', 'instantanée', 0, 'Invoque un esprit prenant la forme d''un petit animal au choix (céleste, fée ou fiélon).'),
('Armure d''Agathys', 1, 'abjuration', '1 action', 'personnelle', 'V, S, M (une coupe d''eau)', '1 heure', 0, 'Gagne 5 PV temporaires. Si touché au CàC pendant ce temps, l''attaquant subit 5 dégâts de froid.'),
('Armure de mage', 1, 'abjuration', '1 action', 'contact', 'V, S, M (un morceau de cuir tanné)', '8 heures', 0, 'La CA d''une cible sans armure passe à 13 + mod Dextérité.'),
('Baies nourricières', 1, 'transmutation', '1 action', 'contact', 'V, S, M (branche de gui)', 'instantanée', 0, 'Fait apparaître 10 baies magiques. Manger une baie rend 1 PV et nourrit pour la journée.'),
('Barbes argentées', 1, 'enchantement', '1 réaction', '18 mètres', 'V', 'instantanée', 0, 'Force une cible ayant réussi un jet à relancer le d20 et prendre le pire. Offre un avantage au prochain jet d''un allié.'),
('Bénédiction', 1, 'enchantement', '1 action', '9 mètres', 'V, S, M (aspersion d''eau bénite)', 'concentration, jusqu''à 1 minute', 0, 'Jusqu''à 3 créatures ajoutent +1d4 à leurs jets d''attaque et de sauvegarde.'),
('Blessure', 1, 'nécromancie', '1 action', 'contact', 'V, S', 'instantanée', 1, 'Attaque au CàC avec un sort. Inflige 3d10 dégâts nécrotiques.'),
('Bouclier', 1, 'abjuration', '1 réaction', 'personnelle', 'V, S', '1 round', 0, 'Accord un bonus de +5 à la CA et annule les dégâts de Projectile Magique jusqu''au prochain tour.'),
('Bouclier de la foi', 1, 'abjuration', '1 action bonus', '18 mètres', 'V, S, M (parchemin saint)', 'concentration, jusqu''à 10 minutes', 0, 'Accorde un bonus de +2 à la CA d''une créature.'),
('Catapulte', 1, 'transmutation', '1 action', '18 mètres', 'S', 'instantanée', 0, 'Projete un objet de 0.5 à 2.5 kg sur 27m. Inflige 3d8 dégâts contondants à l''objet et à la cible (JS Dex).'),
('Cérémonie', 1, 'abjuration (rituel)', '1 heure', 'contact', 'V, S, M (25 po de poudre d''argent)', 'instantanée', 0, 'Réalise un rite religieux (Expiation, Eau bénite, Passage à l''âge adulte, Dévouement, Rite funéraire, Mariage).'),
('Champ protecteur', 1, 'inconnu', '1 action', 'personnelle', 'V, S', '1t', 1, 'Génère un bouclier invisible conférant +2 CA jusqu’au prochain tour. Niveaux supérieurs : +1 CA aux niv 5, 10, 15, 20.'),
('Charme-personne', 1, 'enchantement', '1 action', '9 mètres', 'V, S', '1 heure', 0, 'Tente de charmer un humanoïde. JS Sagesse (avantage si en combat).'),
('Châtiment calcinant', 1, 'évocation', '1 action bonus', 'personnelle', 'V', 'concentration, jusqu''à 1 minute', 1, 'Prochaine attaque CàC inflige +1d6 feu et enflamme la cible (1d6 feu/tour).'),
('Châtiment courroucé', 1, 'évocation', '1 action bonus', 'personnelle', 'V', 'concentration, jusqu''à 1 minute', 1, 'Prochaine attaque CàC inflige +1d6 psychique et effraye la cible (JS Sagesse).'),
('Châtiment tonitruant', 1, 'évocation', '1 action bonus', 'personnelle', 'V', 'concentration, jusqu''à 1 minute', 1, 'Prochaine attaque CàC inflige +2d6 tonnerre, repousse de 3m et fait tomber la cible à terre (JS Force).'),
('Collet', 1, 'abjuration', '1 minute', 'contact', 'S, M (7,5m de corde)', '8 heures', 1, 'Crée un piège magique au sol. La victime (Taille P, M, G) est hissée à l''envers et entravée.'),
('Communication avec les animaux', 1, 'divination (rituel)', '1 action', 'personnelle', 'V, S', '10 minutes', 0, 'Permet de comprendre et communiquer verbalement avec les bêtes.'),
('Compréhension des langues', 1, 'divination (rituel)', '1 action', 'personnelle', 'V, S, M (suie et sel)', '1 heure', 0, 'Comprend la signification littérale de toute langue parlée ou écrite touchée.'),
('Couleurs dansantes', 1, 'illusion', '1 action', 'personnelle (cône de 4,50 mètres)', 'V, S, M (poudre/sable rouge, jaune, bleu)', '1 round', 0, 'Aveugle des créatures dans un cône selon un total de 6d10 PV affectables.'),
('Couteau de glace', 1, 'invocation', '1 action', '18 mètres', 'S, M (goutte d''eau ou glace)', 'instantanée', 0, 'Attaque à distance pour 1d10 perforant + explosion en zone (1,5m) de 2d6 froid (JS Dex).'),
('Création ou destruction d''eau', 1, 'transmutation', '1 action', '9 mètres', 'V, S, M (eau ou sable)', 'instantanée', 1, 'Crée/Détruit 40L d''eau ou pluie/brouillard dans un cube de 9m.'),
('Déguisement', 1, 'illusion', '1 action', 'personnelle', 'V, S', '1 heure', 1, 'Change l''apparence visuelle (vêtements, taille +/- 30cm, corps).'),
('Détection de la magie', 1, 'divination (rituel)', '1 action', 'personnelle', 'V, S', 'concentration, jusqu''à 10 minutes', 1, 'Perçoit la présence de magie à 9m et permet d''en voir l''aura et l''école.'),
('Détection du mal et du bien', 1, 'divination', '1 action', 'personnelle', 'V, S', 'concentration, jusqu''à 10 minutes', 1, 'Détecte aberrations, célestes, élémentaires, fées, fiélons, morts-vivants à 9m.'),
('Détection du poison et des maladies', 1, 'divination (rituel)', '1 action', 'personnelle', 'V, S, M (feuille d''if)', 'concentration, jusqu''à 10 minutes', 1, 'Détecte poisons, créatures venimeuses et maladies à 9m.'),
('Disque flottant de Tenser', 1, 'invocation (rituel)', '1 action', '9 mètres', 'V, S, M (goutte de mercure)', '1 heure', 1, 'Crée une plateforme de force circulaire portant jusqu''à 250 kg qui vous suit.'),
('Duel forcé', 1, 'enchantement', '1 action bonus', '9 mètres', 'V', 'concentration, jusqu''à 1 minute', 0, 'Oblige une cible à engager le duel (désavantage contre les autres, JS Sagesse pour s''éloigner de + de 9m).'),
('Éclair de chaos', 1, 'évocation', '1 action', '36 mètres', 'V, S', 'instantanée', 0, 'Attaque à distance. Inflige 2d8 + 1d6 dégâts (type selon d8). Peut rebondir sur un double.'),
('Éclair traçant', 1, 'évocation', '1 action', '36 mètres', 'V, S', '1 round', 0, 'Attaque à distance pour 4d6 radiants. Le prochain jet d''attaque contre la cible a un avantage.'),
('Élan télékinétique', 1, 'inconnu', '1 action', '2 * m/t du joueur', 'S, V, M', 'instantanée', 1, 'Déplace un allié volontaire de 3 m (sans provocation). Niveau supérieur : +1m/lv pair.'),
('Enchevêtrement', 1, 'invocation', '1 action', '27 mètres', 'V, S', 'concentration, jusqu''à 1 minute', 0, 'Zone de 6m transformée en terrain difficile. JS Force ou entravé par les plantes.'),
('Faveur divine', 1, 'évocation', '1 action bonus', 'personnelle', 'V, S', 'concentration, jusqu''à 1 minute', 0, 'Vos attaques avec une arme infligent +1d4 dégâts radiants.'),
('Feuille morte', 1, 'transmutation', '1 réaction', '18 mètres', 'V, M (plume ou duvet)', '1 minute', 1, 'Ralentit la chute de jusqu''à 5 créatures (18m/round, 0 dégât de chute).'),
('Fléau', 1, 'enchantement', '1 action', '9 mètres', 'V, S, M (goutte de sang)', 'concentration, jusqu''à 1 minute', 0, 'Jusqu''à 3 cibles soustraient 1d4 à leurs jets d''attaque et de sauvegarde (JS Charisme).'),
('Fou rire de Tasha', 1, 'enchantement', '1 action', '9 mètres', 'V, S, M (tartes et plume)', 'concentration, jusqu''à 1 minute', 1, 'Rend une cible hilare. JS Sagesse sous peine de tomber à terre et être incapable d''agir.'),
('Frappe du zéphyr', 1, 'transmutation', '1 action bonus', 'personnelle', 'V', 'concentration, jusqu''à 1 minute', 1, 'Mouvement sans attaque d''opportunité. +1 avantage, +1d8 dégâts de force et +9m vitesse sur une attaque.'),
('Frappe piégeuse', 1, 'invocation', '1 action bonus', 'personnelle', 'V', 'concentration, jusqu''à 1 minute', 0, 'Prochaine attaque entrave la cible dans des lianes (JS Force, 1d6 perforant/tour).'),
('Frayeur', 1, 'nécromancie', '1 action', '18 mètres', 'V', 'concentration, jusqu''à 1 minute', 0, 'Effraye une cible (JS Sagesse). Inefficace sur morts-vivants et artificiels.'),
('Graisse', 1, 'invocation', '1 action', '18 mètres', 'V, S, M (beurre ou couenne)', '1 minute', 0, 'Zone de 3m2 rendue glissante (terrain difficile). JS Dextérité ou chute.'),
('Grande foulée', 1, 'transmutation', '1 action', 'contact', 'V, S, M (pincée de terre)', '1 heure', 1, 'Augmente la vitesse de la cible de 3 mètres.'),
('Grêle d''épines', 1, 'invocation', '1 action bonus', 'personnelle', 'V', 'concentration, jusqu''à 1 minute', 0, 'Prochaine attaque à distance crée une pluie d''épines (1d10 perforant en zone 1,5m, JS Dex).'),
('Héroïsme', 1, 'enchantement', '1 action', 'contact', 'V, S', 'concentration, jusqu''à 1 minute', 1, 'Immunise une cible contre l''effroi et lui donne des PV temp = modificateur d''incantation au début de chaque tour.'),
('Identification', 1, 'divination (rituel)', '1 minute', 'contact', 'V, S, M (perle 100po, plume de hibou)', 'instantanée', 0, 'Révèle les propriétés magiques d''un objet ou les sorts affectant une créature.'),
('Image silencieuse', 1, 'illusion', '1 action', '18 mètres', 'V, S, M (laine de mouton)', 'concentration, jusqu''à 10 minutes', 1, 'Crée l''image visuelle mobile d''un objet/créature dans un cube de 4,50m max.'),
('Injonction', 1, 'enchantement', '1 action', '18 mètres', 'V', '1 round', 0, 'Donne un ordre d''un mot (Approche, Lâche, Fuis, Tombe, Halte). JS Sagesse.'),
('Lien avec une bête', 1, 'divination', '1 action', 'contact', 'V, S, M (fourrure dans un linge)', 'concentration, jusqu''à 10 minutes', 0, 'Lien télépathique avec une bête amicale/charmée (Int < 4). Avantage aux attaques proche du lanceur.'),
('Lueurs féeriques', 1, 'évocation', '1 action', '18 mètres', 'V', 'concentration, jusqu''à 1 minute', 0, 'Entoure d''un halo lumineux les cibles dans un cube de 6m (JS Dex). Avantage aux attaques contre elles, annule l''invisibilité.'),
('Mains brûlantes', 1, 'évocation', '1 action', 'personnelle (cône de 4,50 mètres)', 'V, S', 'instantanée', 0, 'Cône de flammes infligeant 3d6 dégâts de feu (JS Dextérité pour moitié).'),
('Maléfice', 1, 'enchantement', '1 action bonus', '27 mètres', 'V, S, M (œil pétrifié de triton)', 'concentration, jusqu''à 1 heure', 0, 'Maudit une cible : +1d6 dégâts nécrotiques par touche et désavantage sur une caractéristique.'),
('Marque du chasseur', 1, 'divination', '1 action bonus', '27 mètres', 'V', 'concentration, jusqu''à 1 heure', 0, 'Marque une cible : +1d6 dégâts par attaque d''arme et avantage aux jets de Perception/Survie pour la traquer.'),
('Mixture caustique de Tasha', 1, 'évocation', '1 action', 'personnelle (ligne de 9 mètres)', 'V, S, M (nourriture pourrie)', 'concentration, jusqu''à 1 minute', 0, 'Ligne d''acide. 2d4 dégâts d''acide au début de chaque tour de la cible si échec au JS Dex.'),
('Mot de guérison', 1, 'évocation', '1 action bonus', '18 mètres', 'V', 'instantanée', 0, 'Soigne à distance : 1d4 + modificateur d''incantation PV.'),
('Murmures dissonants', 1, 'enchantement', '1 action', '18 mètres', 'V', 'instantanée', 0, 'Mélodie psychique : 3d6 dégâts psychiques et force la cible à fuir en utilisant sa réaction (JS Sagesse).'),
('Nappe de brouillard', 1, 'invocation', '1 action', '36 mètres', 'V, S', 'concentration, jusqu''à 1 heure', 0, 'Sphère de brouillard de 6m de rayon créant une zone de visibilité nulle.'),
('Orbe chromatique', 1, 'évocation', '1 action', '27 mètres', 'V, S, M (diamant 50 po)', 'instantanée', 0, 'Projectiles élémentaires au choix (acide, foudre, feu, froid, poison, tonnerre). Inflige 3d8 dégâts sur touche.'),
('Poigne mentale', 1, 'inconnu', '1 action', '3 * m/t du joueur', 'M', '1min', 1, 'Immobilise un objet ou une créature (taille P). JS Force pour se libérer.'),
('Poussée coordonnée', 1, 'inconnu', '1 action', '2 * m/t du joueur', 'S', 'instantanée', 1, 'Aide un allié en lui donnant un avantage sur son prochain test de Force ou Dextérité.'),
('Projectile élémentaire', 1, 'évocation', '1 action', '27 m', 'V, S, M (pierre précieuse 50 po)', 'instantanée', 0, 'Attaque à distance selon élément choisi (Air, Eau, Feu, Terre) pour 2d8 dégâts + effet secondaire.'),
('Projectile magique', 1, 'évocation', '1 action', '36 mètres', 'V, S', 'instantanée', 0, 'Crée 3 fléchettes infaillibles infligeant chacune 1d4 + 1 dégâts de force.'),
('Protection contre le mal et le bien', 1, 'abjuration', '1 action', 'contact', 'V, S, M (eau bénite/poudre)', 'concentration, jusqu''à 10 minutes', 0, 'Protège la cible contre aberrations, célestes, élémentaires, fées, fiélons et morts-vivants.'),
('Purification de nourriture et d''eau', 1, 'transmutation (rituel)', '1 action', '3 mètres', 'V, S', 'instantanée', 1, 'Purifie la nourriture et la boisson non-magiques dans une sphère de 1,50m.'),
('Rayon empoisonné', 1, 'nécromancie', '1 action', '18 mètres', 'V, S', 'instantanée', 0, 'Attaque à distance pour 2d8 dégâts de poison + JS Constitution pour éviter l''état empoisonné.'),
('Repli expéditif', 1, 'transmutation', '1 action bonus', 'personnelle', 'V, S', 'concentration, jusqu''à 10 minutes', 1, 'Permet d''effectuer l''action Foncer en action bonus à chaque tour.'),
('Représailles infernales', 1, 'évocation', '1 réaction', '18 mètres', 'V, S', 'instantanée', 0, 'Réaction en subissant des dégâts. Entoure l''attaquant de flammes (2d10 feu, JS Dex pour moitié).'),
('Sanctuaire', 1, 'abjuration', '1 action bonus', '9 mètres', 'V, S, M (petit miroir)', '1 minute', 0, 'Force les ennemis ciblant la personne protégée à réussir un JS Sagesse ou changer de cible/perdre l''action.'),
('Saut', 1, 'transmutation', '1 action', 'contact', 'V, S, M (patte de sauterelle)', '1 minute', 1, 'Triple la distance de saut de la cible.'),
('Secousse sismique', 1, 'évocation', '1 action', '3 mètres', 'V, S', 'instantanée', 1, 'Tremblement de terre à 3m. 1d6 contondant + fait tomber à terre (JS Dex). Crée du terrain difficile.'),
('Serviteur invisible', 1, 'invocation (rituel)', '1 action', '18 mètres', 'V, S, M (ficelle et bois)', '1 heure', 0, 'Force invisible qui exécute des tâches ménagères simples à vos ordres.'),
('Simulacre de vie', 1, 'nécromancie', '1 action', 'personnelle', 'V, S, M (alcool)', '1 heure', 0, 'Vous gagnez 1d4 + 4 points de vie temporaires.'),
('Soins', 1, 'évocation', '1 action', 'contact', 'V, S', 'instantanée', 0, 'Soigne une cible touchée : 1d8 + modificateur d''incantation PV.'),
('Sommeil', 1, 'enchantement', '1 action', '27 mètres', 'V, S, M (sable, rose ou grillon)', '1 minute', 0, 'Endort magiquement les créatures en zone (rayon 6m) par ordre croissant de PV (budget de 5d8 PV).'),
('Tentacules de Hadar', 1, 'invocation', '1 action', 'personnelle (rayon de 3 mètres)', 'V, S', 'instantanée', 0, 'Sarments d''énergie autour de vous : 2d6 dégâts nécrotiques et retire la réaction (JS Force pour moitié).'),
('Texte illusoire', 1, 'illusion (rituel)', '1 minute', 'contact', 'S, M (encre de plomb 10po)', '10 jours', 1, 'Rend un texte écrit uniquement lisible par vous et les personnes désignées (inintelligible pour les autres).'),
('Tir Réfléchi', 1, 'inconnu', '1 action', '6m', 'M, S', 'concentration, 1 round', 0, 'Dévie un projectile (d20 + mod CHA vs attaque). Si résultat > +5, peut renvoyer la balle à 6m pour 1d8 dégâts de force.'),
('Trait ensorcelé', 1, 'évocation', '1 action', '9 mètres', 'V, S, M (branche foudroyée)', 'concentration, jusqu''à 1 minute', 0, 'Un rayon lie le lanceur à la cible...');

COMMIT;